# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


format = """
ğŸ‘½ $username
$all

"""
# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# ~/.config/starship.toml
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
home_symbol = "ğŸ "


[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user at]($style) "
disabled = false
show_always = true

[sudo]
style = "bold green"
symbol = "ğŸ”¥ğŸ¦¾"
disabled = false
